# Minimum prek version for builtin hooks and TOML config support
minimum_prek_version = "0.3.2"
# All available: commit-msg, post-checkout, post-commit, post-merge, post-rewrite, pre-commit, pre-merge-commit, pre-push, pre-rebase, prepare-commit-msg
default_install_hook_types = ["commit-msg", "pre-commit", "pre-push"]

[[repos]]
repo = "builtin"
hooks = [
  { id = "no-commit-to-branch", args = ["--branch", "main"], stages = ["pre-commit"], priority = 0 },
  { id = "trailing-whitespace", stages = ["pre-commit"], priority = 0 },
  { id = "end-of-file-fixer", stages = ["pre-commit"], priority = 0 },
  { id = "check-yaml", args = ["--allow-multiple-documents"], stages = ["pre-commit"], priority = 0 },
  { id = "check-toml", stages = ["pre-commit"], priority = 0 },
  { id = "check-added-large-files", stages = ["pre-commit"], priority = 0 },
  { id = "check-merge-conflict", stages = ["pre-commit"], priority = 0 },
  { id = "check-case-conflict", stages = ["pre-commit"], priority = 0 },
  { id = "check-symlinks", stages = ["pre-commit"], priority = 0 },
  { id = "mixed-line-ending", args = ["--fix=lf"], stages = ["pre-commit"], priority = 0 },
  { id = "detect-private-key", stages = ["pre-commit"], priority = 0 },
]

[[repos]]
repo = "https://github.com/gitleaks/gitleaks"
rev = "v8.30.0"
hooks = [{ id = "gitleaks", stages = ["pre-commit"], priority = 1 }]

[[repos]]
repo = "https://github.com/compilerla/conventional-pre-commit"
rev = "v4.3.0"
hooks = [
  { id = "conventional-pre-commit", stages = ["commit-msg"], priority = 1, args = [
    "--strict",
    "--verbose",
    "feat",
    "fix",
    "perf",
    "build",
    "chore",
    "ci",
    "docs",
    "style",
    "refactor",
    "test",
  ] },
]

[[repos]]
repo = "https://github.com/rhysd/actionlint"
rev = "v1.7.10"
hooks = [{ id = "actionlint", stages = ["pre-commit"], priority = 1 }]

[[repos]]
repo = "https://github.com/crate-ci/typos"
rev = "v1.43.4"
hooks = [{ id = "typos", stages = ["pre-commit"], priority = 1 }]

[[repos]]
repo = "https://github.com/igorshubovych/markdownlint-cli"
rev = "v0.47.0"
hooks = [{ id = "markdownlint", args = ["--fix"], stages = ["pre-commit"], priority = 1 }]

[[repos]]
repo = "local"
hooks = [
  { id = "actions-up", name = "Check GitHub Actions updates", language = "system", entry = "env CI=true actions-up --dry-run --yes", stages = ["pre-push"], priority = 1 },
]
